### ISSUE TITLE
pinoDebugWrappedRequire returns "AssertionError: path must be a string" error

### ISSUE THREAD

**Issue by colmose** [pinojs/pino-debug#2]
When I try and run the example server or add pino-debug to an app, this error gets returned from pinoDebugWrappedRequire....

```
ssert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: path must be a string
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at pinoDebugWrappedRequire (c:\Users\Colm-MCQS\Documents\GitHub\pino-debug\example\node_modules\ipaddr.js\li
b\ipaddr.js:14:18)
    at Object.<anonymous> (c:\Users\Colm-MCQS\Documents\GitHub\pino-debug\example\node_modules\ipaddr.js\lib\ipa
ddr.js:17:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

I logged out the script (the variable s) that's passed into the wrapper and the last few lines before the error is thrown is 

```
events
fresh
fs
mime
path
fs
./types.json
ms
on-finished
range-parser
path
statuses
stream
util
path
etag
proxy-addr
forwarded
ipaddr.js
[Function]
```

So the wrapper is being passed a function directly instead of a string but I can't put my finger on where it's being passed in. 

Tried this on windows and *nix, about to give it a go on Mac.

**Comment by mcollina** [comment]
Can you please upload an example that reproduce the problem?

**Comment by colmose** [comment]
The example app in the pino-debug repo is throwing the error as well as any example I will create.
I'm happy to fire something up but it would pretty similar to the example app. 

Steps to repro:
1. Fresh repo clone
2. `npm install` in main directory
3. cd into example folder
4. `npm install` in example folder
5. `npm run start-preload` or `npm run start-programmatic` returns the error. 

Initially without pino or pino-debug installed globally and then after installing both globally. 

This is on Windows, Ubuntu and Mac OS Sierra, all on Node v6.9.2.

I feel like I'm probably doing something stupid here btw.
